### ISSUE TITLE
How to evaluate TinyBeauty model on Makeup Transfer database?

### ISSUE THREAD

**Issue by liangying-Ke** [TinyBeauty/TinyBeauty#6]
Dear Author, 

Thank you for your valuable contribution to the research on makeup transfer. I would like to demonstrate the performance of TinyBeauty model on Makeup Transfer database in our paper. Could you please explain in detail how to utilize the source and reference images from the Makeup Transfer database to evaluate TinyBeauty model?

**Comment by Au233** [comment]
For the DDA model, the makeup template used as conditional injection is considered as a reference. However, if you use inference image ,the effect of applying makeup to images of other people may be affected due to the introduction of other facial information. For the lightweight TinyBeauty model, each model can only apply one type of makeup. If you want to perform makeup transfer, it is almost impossible to accomplish this task with such a lightweight network, which is the original intention behind our proposal of the DDA model to generate paired makeup data.
